


services:
  qdrant:
    image: qdrant/qdrant
    container_name: telesale_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ./storage/qdrant:/qdrant/storage
    networks:
      - telesale_network

  postgres:
    image: postgres:16-alpine
    container_name: telesale_postgres
    restart: unless-stopped
    command: ["postgres", "-c", "timezone=Asia/Ho_Chi_Minh"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: telesale123
      POSTGRES_DB: telesale
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d telesale"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - telesale_network

  redis:
    image: redis:7-alpine
    container_name: telesale_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - telesale_redis_data:/data
    networks:
      - telesale_network

networks:
  telesale_network:
    driver: bridge

volumes:
  telesale_redis_data: